config/routes.rb
Rails.application.routes.draw do
  resources :students
  root to: 'pages#home'
  get 'pages/landing'
  devise_for :users
  resources :roles
  resources :users do
    member do 
      get 'assign_role'
    end
    collection do
      put 'set_role'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
      return unless user

      if user.admin?
        can :manage, :all
      else
        can [:read, :new, :create,], Student if user.create?
        can [:edit, :update, :read], Student if user.edit?
        can [:read, :destroy], Student if user.destroy?
      end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  scope :admin,   -> { where(admin: true)}
  belongs_to :role, optional: true

  def role?
    self.role.name rescue ''
  end

  def edit?
    return self.role.can_edit if role_id.present?
  end

  def create?
    return self.role.can_create if role_id.present?
  end

  def destroy?
    return self.role.can_destroy if role_id.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  def after_sign_in_path_for(resource)
    stored_location_for(resource) || pages_landing_path
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def landing
  end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  def index
    @roles = Role.all
  end

  def show
  end

  def new
    @role = Role.new
  end

  def edit
    @role = Role.find(params['id'])
  end

  def create
    @role = Role.new(role_params)
    if @role.save
      redirect_to roles_path
    else
      format.html { render :new }
    end
  end

  def update
    if @role.update(role_params)
      redirect_to roles_path
    else
      format.html { render :edit }
    end
  end

  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
    end
  end

  private
    def set_role
      @role = Role.find(params[:id])
    end

    def role_params
      params.require(:role).permit(:name, :can_create, :can_edit, :can_destroy)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  load_and_authorize_resource
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
    @students = Student.all
  end

  def show
  end

  def new
    @student = Student.new
  end

  def edit
    @student = Student.find(params['id'])
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to students_path
    else
      format.html { render :new }
    end
  end

  def update
    if @student.update(student_params)
      redirect_to students_path
    else
      format.html { render :edit }
    end
  end

  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
    end
  end

  private
    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:name, :phone, :marks)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  	@users= User.where(admin: false)
  end

  def assign_role
    @user = User.find(params['id'])
  end

  def set_role
    @user = User.find(params['id'])
    @user.update_attributes(role_id: params['user']['role_id'])
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
  <div class="container">
    <%if current_user.present?%>
      <%if !current_user.admin? %>
        <div style="font-size: x-large;color: aliceblue;">Your Role is <%= current_user.role.present? ? current_user.role? : "not assigned yet"%></div>
      <%else%>
        <div style="font-size: x-large;color: aliceblue;">Your Role is Admin</div>
      <%end%>
    <%end%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <%if current_user %>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <%if current_user.admin?%>
            <li class="nav-item">
              <%= link_to 'Roles', roles_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Users', users_path, class: "nav-link" %>
            </li>
          <%end%>
          <li class="nav-item">
            <%= link_to 'Students', students_path, class: "nav-link" %>
          </li>
        <%else%>          
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: "nav-link" %>
          </li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobSearch</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->

    <script src="https://cdn.jsdelivr.net/jquery.validation/1.15.1/jquery.validate.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/header'%>
    <%= render "layouts/alerts"%>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<!-- Page Content -->
<div class="container">
  <h1 class="mt-4">Welcome to Students Portal</h1>
</div>

app/views/pages/landing.html.erb
<h2>Wait for your role assignments.</h2>

app/views/roles/_form.html.erb
<div align="center">
<%= form_with scope: :role, url: roles_path, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 	<p>
    <%= form.label :can_create %><br>
    <%= form.check_box :can_create %>
  </p>
  <p>
    <%= form.label :can_edit %><br>
    <%= form.check_box :can_edit %>
  </p>
  <p>
    <%= form.label :can_destroy %><br>
    <%= form.check_box :can_destroy %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
</div>

app/views/roles/edit.html.erb
<div align="center">
  <%= form_for @role, url: role_path, method: :put do |f| %>
    <p> 
      <%f.label :name %>
      <%= f.text_field :name  %>
    </p>
    <p>
      <%= f.label :can_create %><br>
      <%= f.check_box :can_create %>
    </p>
    <p>
      <%= f.label :can_edit %><br>
      <%= f.check_box :can_edit %>
    </p>
    <p>
      <%= f.label :can_destroy %><br>
      <%= f.check_box :can_destroy %>
    </p>
    <p>
      <%= f.submit %>
    </p>
</div>
<% end %>

app/views/roles/index.html.erb
<div align="center">
  <table>
    <%= link_to "Add Roles", new_role_path%>
    <head>
      <title>Roles</title>
    </head>
    <body>
      <table border = "1" cellpadding = "10" cellspacing = "10" width="50%" height="20px" style="text-align: center;">
        <tr>
          
        </tr>
        <tbody>
        <% @roles.each do |role| %>
          <tr class = "">
            <td height="20"><%=role.name%></td>
            <td><%= link_to 'Show', role_path(role) %></td>
            <td><%= link_to 'Edit', edit_role_path(role.id) %></td>
            <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <%end%>
        </tbody>
      </table>
    </body>
  </table>
</div>  

app/views/roles/new.html.erb
<div align="center">
<h1>New Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Back', roles_path %>
</div>

app/views/roles/show.html.erb
<div align="center">
<p><%= @role.name %></p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>
</div>

app/views/students/_form.html.erb
<div align="center">
<%= form_with scope: :student, url: students_path, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 	<p>
    <%= form.label :phone %><br>
    <%= form.text_field :phone %>
  </p>
  <p>
    <%= form.label :marks %><br>
    <%= form.number_field :marks %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
</div>

app/views/students/edit.html.erb
<div align="center">
  <%= form_for @student, url: student_path, method: :put do |f| %>
    <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 	<p>
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </p>
  <p>
    <%= f.label :marks %><br>
    <%= f.number_field :marks %>
  </p>
  <p>
    <%= f.submit %>
  </p>
</div>
<% end %>

app/views/students/index.html.erb
<div align="center">
  <table>
    <% if can? :create, Student%>
      <%= link_to "Add Students", new_student_path%>
    <%end%>
    <head>
      <title>Students</title>
    </head>
    <body>
      <table border = "1" cellpadding = "10" cellspacing = "10" width="50%" height="20px" style="text-align: center;">
        <tr>
          
        </tr>
        <tbody>
        <% @students.each do |student| %>
          <tr class = "">
            <td height="20"><%=student.name%></td>
            <td height="20"><%=student.marks%></td>
            <td height="20"><%=student.phone%></td>
            <td><%= link_to 'Show', student_path(student) %></td> 
            <td><%= link_to 'Edit', edit_student_path(student.id) if can? :edit, Student %></td>
            <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } if can? :destroy, Student %></td>
          </tr>
        <%end%>
        </tbody>
      </table>
    </body>
  </table>
</div>  

app/views/students/new.html.erb
<div align="center">
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>
</div>

app/views/students/show.html.erb
<div align="center">
<p><%= @student.name %></p>
<p><%= @student.marks %></p>
<p><%= @student.phone %></p>

<%= link_to 'Edit', edit_student_path(@student)  if can? :edit, Student %> |
<%= link_to 'Back', students_path %>
</div>

app/views/users/assign_role.html.erb
<div align="center">
<div class="col-md-3">
  <div align="left" >
    <%= form_for(@user, url: set_role_users_path(id: @user.id), html: { method: :put }) do |f| %>
      <%= f.select :role_id, Role.all.map{|l| [l.name, l.id]}, { include_blank: "Select Role" } %>
      <%= f.submit %>
    <% end %>
  </div> 
</div> 
</div>

app/views/users/index.html.erb
<div align="center">
  <table>
    <head>
      <title>Roles</title>
    </head>
    <body>
      <table border = "1" cellpadding = "10" cellspacing = "10" width="50%" height="20px" style="text-align: center;">
        <tr>
          
        </tr>
        <tbody>
        <% @users.each do |user| %>
          <tr class = "">
            <td height="20"><%= user.email %></td>
            <td> <%= user.role.name rescue '' %></td>
            <td><%= link_to "Assign role", assign_role_user_path(user.id) %></td>
          </tr>
        <%end%>
        </tbody>
      </table>
    </body>
  </table>
</div>  